---
doAutologin: false
setRootPassword: false
sudoersGroup: sudo
defaultGroups:
  - adm
  - cdrom
  - dip
  - lpadmin
  - plugdev
  - sudo
passwordRequirements:
  minLength: 8
  maxLength: -1
user:
  shell: /bin/bash
  forbidden_names: [root]
