---
# No GeoIP; do not require network (offline installs).
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false
showDonateUrl: false

requirements:
  requiredStorage: 8
  requiredRam: 0.5
  check:
    - storage
    - ram
    - power
    - root
  required:
    - root
    - storage
    - ram
