# SPDX-License-Identifier: MIT
# Vanilla Ubuntu live ISO — Calamares only (no calamares-settings-* packages).
# Uses stock Calamares modules from the calamares binary package + YAML below.
---
modules-search: [ local ]

instances:
  - id: bug-LP#1829805
    module: shellprocess
    config: shellprocess_bug-LP#1829805.conf
  - id: lxde-repair
    module: shellprocess
    config: shellprocess_lxde-repair.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - luksbootkeyfile
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - shellprocess@bug-LP#1829805
      - initramfscfg
      - initramfs
      - grubcfg
      - bootloader
      - shellprocess@lxde-repair
      - packages
      - umount
  - show:
      - finished

branding: ubuntu
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
